version: '2'
services:
  mysql:
    container_name: finerink_mysql
    restart: always
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'finerinkprod'
      MYSQL_ROOT_PASSWORD: 'FinerInk'
      MYSQL_USER: 'finerAdmin'
      MYSQL_PASSWORD: 'finerPass'
    volumes:
      - ./mysql/data/db:/var/lib/mysql
      - ./mysql/data/schema/:/docker-entrypoint-initdb.d/
  redis:
    container_name: finerink_redis
    restart: always
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./redis/data:/bitnami