version: '2'
services:
  mysql:
    container_name: finerink_mysql
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'finerinkprod'
      MYSQL_ROOT_PASSWORD: 'FinerInk'
      MYSQL_USER: 'finerAdmin'
      MYSQL_PASSWORD: 'finerPass'
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/schema/:/docker-entrypoint-initdb.d/